name: Setup Poetry

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-python@v1
    with:
      python-version: 3.8
  - uses: Gr1N/setup-poetry@v4
  - run: poetry --version

branding:
  icon: package
  color: purple