name: Auto pytest with codecov

on: [push]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Test with pytest
        run: poetry run pytest

      - name: Generate code coverage report
        run: poetry run pytest --cov-report xml --cov=pyexplainer tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true